In [1]:
import numpy as np
import math



ans_mtx = [[-1.00000000e+00,  9.38133875e-17, -7.87187789e-17, 6.25000000e+02],
           [ 1.22464680e-16,  7.66044443e-01, -6.42787610e-01, 1.95000000e+02],
           [ 0.00000000e+00, -6.42787610e-01, -7.66044443e-01, 2.25000000e+02],
           [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]]

identity_mtx = [[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00],
                [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, 0.00000000e+00],
                [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, 0.00000000e+00],
                [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]]



test_mtx_trns = [[-0.988585829734802,-0.146967247128487,-0.0331470519304276,655.248474121094],
[-0.0840407311916351,0.720544755458832,-0.688296735286713,69.133918762207],
[0.125041007995605,-0.677654683589935,-0.724671602249146,215.395294189453],
[0,0,0,1]]

test_mtx_err = [[0.988585412502289,-0.0912774279713631,0.119863495230675,1.26573240756989],
[0.0840407833456993,0.994397759437561,0.0641110613942146,2.24798822402954],
[-0.125043883919716,-0.0533058419823647,0.990718185901642,-1.64789760112762],
[0,0,0,1]]

test_mtx_id = [[0.999998331069946,0.00172358111012727,-0.000586170644965023,-0.0312805958092213],
               [-0.00172355852555484,0.999998509883881,3.90266613976564E-05,0.0254219025373459],
               [0.000586237059906125,-3.80162964574993E-05,0.999999821186066,-0.0108767841011286],
               [0,0,0,1]]

In [2]:
ans_mtx_ = np.array(ans_mtx)
identity_mtx = np.array(identity_mtx)

In [3]:
test_mtx_trns_ = np.array(test_mtx_trns)
test_mtx_err_ = np.array(test_mtx_err)
test_mtx_id_ = np.array(test_mtx_id)

In [4]:
ans_mtx_ - test_mtx_trns_

array([[-1.14141703e-02,  1.46967247e-01,  3.31470519e-02,
        -3.02484741e+01],
       [ 8.40407312e-02,  4.54996875e-02,  4.55091253e-02,
         1.25866081e+02],
       [-1.25041008e-01,  3.48670736e-02, -4.13728408e-02,
         9.60470581e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [5]:
identity_mtx - test_mtx_err_

array([[ 0.01141459,  0.09127743, -0.1198635 , -1.26573241],
       [-0.08404078,  0.00560224, -0.06411106, -2.24798822],
       [ 0.12504388,  0.05330584,  0.00928181,  1.6478976 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [6]:
identity_mtx - test_mtx_id_

array([[ 1.66893005e-06, -1.72358111e-03,  5.86170645e-04,
         3.12805958e-02],
       [ 1.72355853e-03,  1.49011612e-06, -3.90266614e-05,
        -2.54219025e-02],
       [-5.86237060e-04,  3.80162965e-05,  1.78813934e-07,
         1.08767841e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [7]:
def mtx2euler(mtx) :
    dLocSqrt = (mtx[0][0] * mtx[0][0] +  mtx[1][0] * mtx[1][0])
    
    if(dLocSqrt<0.0):
        dLocSqrt = 0.0
    else:
        dLocSqrt= math.sqrt(dLocSqrt)
    
    dLocRy = math.atan2(-mtx[2][0], dLocSqrt)
    dLocCy = math.cos(dLocRy)
 
    if (dLocCy < 0.001745328365898):
        Rx = 0.0
        Ry = dLocRy
        Rz = math.atan2(-mtx[0][1], mtx[1][1])
    else:
        Rx = math.atan2(mtx[2][1]/dLocCy, mtx[2][2]/dLocCy)
        Ry = dLocRy
        Rz = math.atan2(mtx[1][0]/dLocCy, mtx[0][0]/dLocCy)
        
    X = mtx[0][3]
    Y = mtx[1][3]
    Z = mtx[2][3]
    Rx = Rx * 180 / 3.141592653589793238462643383279
    Ry = Ry * 180 / 3.141592653589793238462643383279
    Rz = Rz * 180 / 3.141592653589793238462643383279
 
    return np.array([X, Y, Z, Rx, Ry, Rz])

coarse iter : 47  
coarse RMSE : 0.158407  
fine iter : 100  
fine RMSE : 0.085638  
fine RMSE all pts : 0.157545                 

In [13]:
mtx2euler(np.absolute(ans_mtx_)) - mtx2euler(np.absolute(np.linalg.inv(test_mtx_trns_)))

array([-1.64615041,  2.55039641, -0.39504067, -3.52532898,  1.89953384,
       -8.45589533])

coarse iter : 47  
coarse RMSE : 0.158406  
fine iter : 100  
fine RMSE : 0.085640  
fine RMSE all pts : 0.157544                 

In [9]:
mtx2euler(np.absolute(identity_mtx)) - mtx2euler(np.absolute(np.linalg.inv(test_mtx_err_)))

array([-1.64626688, -2.20770425, -1.33676608, -3.70254516,  6.88422447,
       -5.27524001])

coarse iter : 28  
coarse RMSE : 0.133318  
fine iter : 81  
fine RMSE : 0.006778  
fine RMSE all pts : 0.140962  

In [62]:
mtx2euler(np.absolute(identity_mtx)) - mtx2euler(np.absolute(np.linalg.inv(test_mtx_id_)))

array([ 0.03133074,  0.02536836,  0.01085745,  0.00223606, -0.03358511,
        0.09875399])

###### mtx tracking

In [42]:
mtx2euler(ans_mtx_)

array([ 625.        ,  195.        ,  225.        , -139.99999998,
         -0.        ,  180.        ])