In [32]:
import numpy as np
import math



ans_mtx = [[-1.00000000e+00,  9.38133875e-17, -7.87187789e-17, 6.25000000e+02],
           [ 1.22464680e-16,  7.66044443e-01, -6.42787610e-01, 1.95000000e+02],
           [ 0.00000000e+00, -6.42787610e-01, -7.66044443e-01, 2.25000000e+02],
           [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]]

identity_mtx = [[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00],
                [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, 0.00000000e+00],
                [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, 0.00000000e+00],
                [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]]



test_mtx_trns = [[-0.987133145332336,-0.119844101369381,-0.105856440961361,664.762939453125],
[-0.00612966762855649,0.689889013767242,-0.723889172077179,32.2285499572754],
[0.1597830504179,-0.713926136493683,-0.681746900081635,190.968826293945],
[0,0,0,1]]

test_mtx_err = [[0.987133145332336,-0.0237627644091845,0.158125087618828,0.617424190044403],
[0.00612968578934669,0.993792653083801,0.111079424619675,0.0508073270320892],
[-0.159783095121384,-0.108680926263332,0.981151282787323,-1.77542269229889],
[0,0,0,1]]

test_mtx_id = [[0.999998331069946,0.00172358111012727,-0.000586170644965023,-0.0312805958092213],
               [-0.00172355852555484,0.999998509883881,3.90266613976564E-05,0.0254219025373459],
               [0.000586237059906125,-3.80162964574993E-05,0.999999821186066,-0.0108767841011286],
               [0,0,0,1]]

In [33]:
ans_mtx_ = np.array(ans_mtx)
identity_mtx = np.array(identity_mtx)

In [34]:
test_mtx_trns_ = np.array(test_mtx_trns)
test_mtx_err_ = np.array(test_mtx_err)
test_mtx_id_ = np.array(test_mtx_id)

In [35]:
ans_mtx_ - test_mtx_trns_

array([[-1.28668547e-02,  1.19844101e-01,  1.05856441e-01,
        -3.97629395e+01],
       [ 6.12966763e-03,  7.61554292e-02,  8.11015621e-02,
         1.62771450e+02],
       [-1.59783050e-01,  7.11385265e-02, -8.42975429e-02,
         3.40311737e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [36]:
identity_mtx - test_mtx_err_

array([[ 0.01286685,  0.02376276, -0.15812509, -0.61742419],
       [-0.00612969,  0.00620735, -0.11107942, -0.05080733],
       [ 0.1597831 ,  0.10868093,  0.01884872,  1.77542269],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [37]:
identity_mtx - test_mtx_id_

array([[ 1.66893005e-06, -1.72358111e-03,  5.86170645e-04,
         3.12805958e-02],
       [ 1.72355853e-03,  1.49011612e-06, -3.90266614e-05,
        -2.54219025e-02],
       [-5.86237060e-04,  3.80162965e-05,  1.78813934e-07,
         1.08767841e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [38]:
def mtx2euler(mtx) :
    dLocSqrt = (mtx[0][0] * mtx[0][0] +  mtx[1][0] * mtx[1][0])
    
    if(dLocSqrt<0.0):
        dLocSqrt = 0.0
    else:
        dLocSqrt= math.sqrt(dLocSqrt)
    
    dLocRy = math.atan2(-mtx[2][0], dLocSqrt)
    dLocCy = math.cos(dLocRy)
 
    if (dLocCy < 0.001745328365898):
        Rx = 0.0
        Ry = dLocRy
        Rz = math.atan2(-mtx[0][1], mtx[1][1])
    else:
        Rx = math.atan2(mtx[2][1]/dLocCy, mtx[2][2]/dLocCy)
        Ry = dLocRy
        Rz = math.atan2(mtx[1][0]/dLocCy, mtx[0][0]/dLocCy)
        
    X = mtx[0][3]
    Y = mtx[1][3]
    Z = mtx[2][3]
    Rx = Rx * 180 / 3.141592653589793238462643383279
    Ry = Ry * 180 / 3.141592653589793238462643383279
    Rz = Rz * 180 / 3.141592653589793238462643383279
 
    return np.array([X, Y, Z, Rx, Ry, Rz])

coarse iter : 100  
coarse RMSE : 0.269731  
fine iter : 100  
fine RMSE : 0.119575  
fine RMSE all pts : 0.260448  

In [57]:
mtx2euler(np.absolute(ans_mtx_)) - mt x2euler(np.absolute(np.linalg.inv(test_mtx_trns_)))

array([-0.89347312,  1.22856892,  1.10825147, -6.7172669 ,  6.0765122 ,
       -6.92218711])

coarse iter : 100  
coarse RMSE : 0.269732  
fine iter : 100  
fine RMSE : 0.119573  
fine RMSE all pts : 0.260449  

In [58]:
mtx2euler(np.absolute(identity_mtx)) - mtx2euler(np.absolute(np.linalg.inv(test_mtx_err_)))

array([-0.89347381, -0.22877481, -1.63868432, -6.45914489,  9.09808592,
       -1.37898636])

coarse iter : 28  
coarse RMSE : 0.133318  
fine iter : 81  
fine RMSE : 0.006778  
fine RMSE all pts : 0.140962  

In [59]:
mtx2euler(np.absolute(identity_mtx)) - mtx2euler(np.absolute(np.linalg.inv(test_mtx_id_)))

array([-0.03133074, -0.02536836, -0.01085745, -0.00223606,  0.03358511,
       -0.09875399])

###### mtx tracking

In [42]:
mtx2euler(ans_mtx_)

array([ 625.        ,  195.        ,  225.        , -139.99999998,
         -0.        ,  180.        ])