In [1]:
import numpy as np
import math
from xml.etree.ElementTree import parse
import glob
import pprint

In [2]:
init_plan_data_path = 'C:/Users/eornr/Desktop/source_crx/200331_point_gen/01_point_gen_in_STL/05_gen_point_init_planing_data/raw_data/'

file_ext = '.xml'
xml_data_name = ['c1L_plan', 
                 'c1R_plan', 
                 'c2L_plan', 
                 'c2R_plan']

femur_imp_model_mtx = []
tibia_imp_model_mtx = []

for fi in range(len(xml_data_name)):
    tree = parse(init_plan_data_path + xml_data_name[fi] + file_ext)
    main_root = tree.getroot()

    femur_imp_model = main_root.getchildren()[2].getchildren()[1].getchildren()[0]
    tibia_imp_model = main_root.getchildren()[3].getchildren()[1].getchildren()[0]
    
    value_split_f = femur_imp_model.find("MatrixModel2Local").text.split(',')
    value_split_t = tibia_imp_model.find("MatrixModel2Local").text.split(',')
    
    femur_imp_model_mtx.append(value_split_f)
    tibia_imp_model_mtx.append(value_split_t)

In [3]:
def mtx_value_list_2_mtx_array(mtx_value_list):
    mtx_array = []
    
    count = 0
    for i in range(4):
        tmp = []
        for j in range(4):
            tmp.append(float(mtx_value_list[j + count]))
        count = count + 4
        mtx_array.append(tmp)
        
    return mtx_array

def mtx2euler(mtx) :
    dLocSqrt = (mtx[0][0] * mtx[0][0] +  mtx[1][0] * mtx[1][0])
    
    if(dLocSqrt<0.0):
        dLocSqrt = 0.0
    else:
        dLocSqrt= math.sqrt(dLocSqrt)
    
    dLocRy = math.atan2(-mtx[2][0], dLocSqrt)
    dLocCy = math.cos(dLocRy)
 
    if (dLocCy < 0.001745328365898):
        Rx = 0.0
        Ry = dLocRy
        Rz = math.atan2(-mtx[0][1], mtx[1][1])
    else:
        Rx = math.atan2(mtx[2][1]/dLocCy, mtx[2][2]/dLocCy)
        Ry = dLocRy
        Rz = math.atan2(mtx[1][0]/dLocCy, mtx[0][0]/dLocCy)
        
    X = mtx[0][3]
    Y = mtx[1][3]
    Z = mtx[2][3]
    Rx = Rx * 180 / 3.141592653589793238462643383279
    Ry = Ry * 180 / 3.141592653589793238462643383279
    Rz = Rz * 180 / 3.141592653589793238462643383279
 
    return np.array([X, Y, Z, Rx, Ry, Rz])

In [4]:
femur_imp_mtxs = []
tibia_imp_mtxs = []

for i in range(4):
    femur_imp_mtxs.append(np.array(mtx_value_list_2_mtx_array(femur_imp_model_mtx[i])))
    tibia_imp_mtxs.append(np.array(mtx_value_list_2_mtx_array(tibia_imp_model_mtx[i])))

### read sim. data!!

In [5]:
result_data_path = 'C:/Users/eornr/Desktop/source_crx/200331_point_gen/01_point_gen_in_STL/06_gen_point_data_proto/result/'
mtx_str = 'mtx'
log_str = 'log'

In [6]:
result_files = glob.glob(result_data_path + '*')

In [7]:
ans_mtx      = [[-1.00000000e+00,  9.38133875e-17, -7.87187789e-17, 6.25000000e+02],
                [ 1.22464680e-16,  7.66044443e-01, -6.42787610e-01, 1.95000000e+02],
                [ 0.00000000e+00, -6.42787610e-01, -7.66044443e-01, 2.25000000e+02],
                [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]]

identity_mtx = [[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00],
                [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, 0.00000000e+00],
                [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, 0.00000000e+00],
                [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]]

### pose + 400 test

In [8]:
mtx_of_exp = []

for i in range(len(result_files)):
    file_path_str = result_files[i]
    if(log_str in file_path_str):
        with open(file_path_str) as file:
            for line in file:
                print(line)
    elif(mtx_str in file_path_str):
        with open(file_path_str) as file:
            for line in file:
                _line = line.split('\n')
                each_value = _line[0].split(',')
                tmp = []
                for i in range(len(each_value)):
                    tmp.append(float(each_value[i]))
                mtx_of_exp.append(tmp)
                
mtx_of_exp = np.array(mtx_of_exp)

coarse iter : 100

coarse RMSE : 0.192846

fine iter : 100

fine RMSE : 0.083711

fine RMSE all pts : 0.192116



In [9]:
mtx2euler(np.absolute(ans_mtx)) - mtx2euler(np.absolute(np.linalg.inv(mtx_of_exp)))

array([-2.36191153,  3.12658869, -0.40422279, -3.86834518,  2.31459522,
       -7.97823144])

In [10]:
indexer = 0
result = (mtx2euler(np.absolute(np.dot(ans_mtx, 
                                       femur_imp_mtxs[indexer]))) - 
          mtx2euler(np.absolute(np.dot(np.linalg.inv(mtx_of_exp), 
                                       femur_imp_mtxs[indexer]))))
result

array([-1.61739616,  1.66542058, -0.53259952, -3.86834518,  2.31459522,
       -7.97823144])

###### in implant space...

In [11]:
# Te = (pose * plan)^-1 * regi. * plan
Te = np.dot(np.dot(np.linalg.inv(np.dot(ans_mtx, femur_imp_mtxs[indexer])), np.linalg.inv(mtx_of_exp)), femur_imp_mtxs[indexer])
mtx2euler(Te)

array([-1.61739616, -1.61790579,  0.66307499,  3.98647865, -6.89842267,
       -4.63579551])

### 400 test

In [18]:
mtx_of_exp = []

for i in range(len(result_files)):
    file_path_str = result_files[i]
    if(log_str in file_path_str):
        with open(file_path_str) as file:
            for line in file:
                print(line)
    elif(mtx_str in file_path_str):
        with open(file_path_str) as file:
            for line in file:
                _line = line.split('\n')
                each_value = _line[0].split(',')
                tmp = []
                for i in range(len(each_value)):
                    tmp.append(float(each_value[i]))
                mtx_of_exp.append(tmp)
                
mtx_of_exp = np.array(mtx_of_exp)

coarse iter : 34

coarse RMSE : 0.098521

fine iter : 2

fine RMSE : 0.034340

fine RMSE all pts : 0.098684



In [19]:
mtx2euler(np.absolute(identity_mtx)) - mtx2euler(np.absolute(np.linalg.inv(mtx_of_exp)))

array([-2.18138859, -0.64983151, -0.82372527, -1.30336284,  2.07725627,
       -2.84299431])

In [20]:
indexer = 0
result = (mtx2euler(np.absolute(np.dot(identity_mtx, 
                                       femur_imp_mtxs[indexer]))) - 
          mtx2euler(np.absolute(np.dot(np.linalg.inv(mtx_of_exp), 
                                       femur_imp_mtxs[indexer]))))
result

array([-0.74477846,  0.34129699, -0.41680656, -1.26382875,  2.07725627,
       -2.84299431])

###### in implant space...

In [21]:
# Te = (pose * plan)^-1 * regi. * plan
Te = np.dot(np.dot(np.linalg.inv(np.dot(identity_mtx, femur_imp_mtxs[indexer])), np.linalg.inv(mtx_of_exp)), femur_imp_mtxs[indexer])
mtx2euler(Te)

array([ 0.74477846,  0.34115315, -0.41692425, -1.30335148,  2.07627559,
       -2.84371005])

### 40 test

In [112]:
mtx_of_exp = []

for i in range(len(result_files)):
    file_path_str = result_files[i]
    if(log_str in file_path_str):
        with open(file_path_str) as file:
            for line in file:
                print(line)
    elif(mtx_str in file_path_str):
        with open(file_path_str) as file:
            for line in file:
                _line = line.split('\n')
                each_value = _line[0].split(',')
                tmp = []
                for i in range(len(each_value)):
                    tmp.append(float(each_value[i]))
                mtx_of_exp.append(tmp)
                
mtx_of_exp = np.array(mtx_of_exp)

coarse iter : 40

coarse RMSE : 0.271314

fine iter : 53

fine RMSE : 0.085713

fine RMSE all pts : 0.278881



In [113]:
mtx2euler(np.absolute(identity_mtx)) - mtx2euler(np.absolute(np.linalg.inv(mtx_of_exp)))

array([-0.05887913, -0.02890516, -0.13252821, -0.0041252 ,  0.0562453 ,
       -0.04231434])

In [114]:
indexer = 0
result = (mtx2euler(np.absolute(np.dot(identity_mtx, 
                                       femur_imp_mtxs[indexer]))) - 
          mtx2euler(np.absolute(np.dot(np.linalg.inv(mtx_of_exp), 
                                       femur_imp_mtxs[indexer]))))
result

array([-0.08724545, -0.03003709, -0.13127775,  0.0041252 ,  0.0562453 ,
       -0.04231434])

###### in implant space...

In [115]:
# Te = (pose * plan)^-1 * regi. * plan
Te = np.dot(np.dot(np.linalg.inv(np.dot(identity_mtx, femur_imp_mtxs[indexer])), np.linalg.inv(mtx_of_exp)), femur_imp_mtxs[indexer])
mtx2euler(Te)

array([-0.08727545, -0.03008238, -0.13126737, -0.0041252 ,  0.05623069,
       -0.04233374])

### 자가 정합 40

coarse iter : 28  
coarse RMSE : 0.133318  
fine iter : 81  
fine RMSE : 0.006778  
fine RMSE all pts : 0.140962  

In [86]:
test_mtx_id = [[0.999998331069946,0.00172358111012727,-0.000586170644965023,-0.0312805958092213],
               [-0.00172355852555484,0.999998509883881,3.90266613976564E-05,0.0254219025373459],
               [0.000586237059906125,-3.80162964574993E-05,0.999999821186066,-0.0108767841011286],
               [0,0,0,1]]

test_mtx_id_ = np.array(test_mtx_id)

In [87]:
mtx2euler(np.absolute(identity_mtx)) - mtx2euler(np.absolute(np.linalg.inv(test_mtx_id_)))

array([-0.03133074, -0.02536836, -0.01085745, -0.00223606,  0.03358511,
       -0.09875399])

In [88]:
indexer = 0
result = (mtx2euler(np.absolute(np.dot(identity_mtx, 
                                       femur_imp_mtxs[indexer]))) - 
          mtx2euler(np.absolute(np.dot(np.linalg.inv(test_mtx_id_), 
                                       femur_imp_mtxs[indexer]))))
result

array([-0.05173189, -0.02473668,  0.01018653, -0.00223606,  0.03358511,
       -0.09875399])

###### in implant space...

In [119]:
# Te = (pose * plan)^-1 * regi. * plan
Te = np.dot(np.dot(np.linalg.inv(np.dot(identity_mtx, femur_imp_mtxs[indexer])), np.linalg.inv(test_mtx_id_)), femur_imp_mtxs[indexer])
mtx2euler(Te)

array([ 0.05173189, -0.02473316,  0.01019506,  0.00223609,  0.03361917,
        0.09874239])
